language: generic
sudo: required
dist: trusty
os:
 - linux

env:
  global:
  - RACKET_DIR=~/racket
  - WWW_DIR=/fs/www/class
  - PANDOC=~/.pandoc
  - PANDOC_DEB="https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-1-amd64.deb"
  matrix:
  - RACKET_VERSION=7.4
  
cache:
  directories:
    - $PANDOC

before_install:
- mkdir -p "$PANDOC"
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then if [[ ! -f "$PANDOC/pandoc.deb" ]]; then curl -L "$PANDOC_DEB" > "$PANDOC/pandoc.deb" && dpkg -x "$PANDOC/pandoc.deb" "$PANDOC"; fi ; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then export PATH="$PANDOC/usr/bin:$PATH"; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then git clone https://github.com/greghendershott/travis-racket.git; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then cat travis-racket/install-racket.sh | bash; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then export PATH="${RACKET_DIR}/bin:${PATH}"; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y nasm; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew cask install racket; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install nasm; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install pandoc; fi

install: 

before_script:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then export DISPLAY=:99.0; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sh -e /etc/init.d/xvfb start; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sleep 3; fi

script:
- raco make www/main.scrbl
- raco test www
- make -C www main
- mv www/main www/cmsc430

addons:
  ssh_known_hosts: junkfood.cs.umd.edu
before_deploy:
- openssl aes-256-cbc -K $encrypted_38f5f53c68a8_key -iv $encrypted_38f5f53c68a8_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
- provider: script
  skip_cleanup: true
  script: rsync -rvzp $TRAVIS_BUILD_DIR/www/cmsc430 dvanhorn@junkfood.cs.umd.edu:$WWW_DIR/spring2020
  on:
    branch: master
    condition: "$TRAVIS_OS_NAME = linux"

