on:
  - push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Install dependencies
      run: |
        sudo apt-get install pandoc
        sudo apt-get install nasm
    - name: Install Racket
      uses: Bogdanp/setup-racket@v0.10
      with:
        architecture: 'x64'
        distribution: 'full'
        version: '7.9'
    - name: Build and test
      run: |
        raco make www/main.scrbl
	raco test www
	make -C www main
    - name: Archive www
      uses: actions/upload-artifact@v2
      with:
        name: www
        path: www/cmsc430
